

export const TYPES={

    ADD_TO_CART : "ADD_TO_CART",
    REMOVE_ONE_FROM_CART: "REMOVE_ONE_FROM_CART",
    REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
    CLEAR_CART: "CLEAR_CART",
    SET_CART_FROM_STORAGE: 'SET_CART_FROM_STORAGE',
    ADD_TALLA :"ADD_TALLA",
    QUANTITY: "QUANTITY",
    TOTAL:"TOTAL",
    SET_TOKEN:"SET_TOKEN",
    LOGOUT:"LOGOUT",
    SESS_TOKEN:"SESS_TOKEN"
};
